apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: frontend
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-front.git
        targetRevision: HEAD
        path: chart/front
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: product
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-Product.git
        targetRevision: HEAD
        path: chart/product
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: order
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-Order.git
        targetRevision: HEAD
        path: chart/order
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: user
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-User.git
        targetRevision: HEAD
        path: chart/user
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: rating
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-Rating.git
        targetRevision: HEAD
        path: chart/rating
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: cart
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    namespace: argo
spec:
    project: default
    source:
        repoURL: https://github.com/sjoh0704/All-In-One-Cart.git
        targetRevision: HEAD
        path: chart/cart
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
            allowEmpty: false
