apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello  
spec:
  entrypoint: test  # the first template to run in the workflows        
  templates:
  - name: test
    resource:
      action: create
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          creationTimestamp: null
          labels:
            run: pod
          name: pod
        spec:
          containers:
          - image: nginx
            name: pod
            ports:
            - containerPort: 80

