apiVersion: v1
kind: Service
metadata:
  name: api-gw
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api-gw
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: ClusterIP