apiVersion: v1
kind: ConfigMap
metadata:
  name: user-url
  namespace: {{ .Release.Namespace }}
data:
  ORDER_SERVICE_URL: 'http://order.{{ .Release.Namespace }}.svc:8080'
  PRODUCT_SERVICE_URL: 'http://product.{{ .Release.Namespace }}.svc:8080'
  CART_SERVICE_URL: 'http://cart.{{ .Release.Namespace }}.svc:8080'
  RATING_SERVICE_URL: 'http://rating.{{ .Release.Namespace }}.svc:8080'
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_ID: 'root'
  MYSQL_ROOT_PASSWORD: 'root' ## TODO secret으로 빼기 
  MYSQL_DB: 'user'
  MYSQL_HOST: 'user-db.{{ .Release.Namespace }}.svc'
