apiVersion: v1
kind: Service
metadata:
  name:  user
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- else if eq .Values.app.service.type "LoadBalancer" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  type: {{ .Values.app.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: user-db
