server:
  service:
    type: NodePort
    nodePortHttp: 30000

dex:
  enabled: false

# redis:
#   enabled: false

notifications:
  enabled: false

## TODO Appication set이 필요한지 생각
applicationSet:
  # -- Enable Application Set controller
  enabled: false