apiVersion: v1
kind: Service
metadata:
  name:  order
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: order
  ports:
    - name: http
      port: 8080
      targetPort: 8000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "LoadBalancer" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: order-db
