apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-url
  namespace: {{ .Release.Namespace }}
data:
  PRODUCT_SERVICE_URL: 'http://product.{{ .Release.Namespace }}.svc:8080'
  USER_SERVICE_URL: 'http://user.{{ .Release.Namespace }}.svc:8080'
  RATING_SERVICE_URL: 'http://rating.{{ .Release.Namespace }}.svc:8080'
  ORDER_SERVICE_URL: 'http://order.{{ .Release.Namespace }}.svc:8080'  

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-db
data:
  MONGO_HOST: 'cart-db.{{ .Release.Namespace }}.svc:27017'
