apiVersion: v1
kind: Service
metadata:
  name:  cart
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      {{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- else if eq .Values.app.service.type "LoadBalancer" }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  type: {{ .Values.app.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: cart-db
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: cart-db
