front:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

cart:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

user:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

product:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

order:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

rating:
  source:
    repoURL: https://github.com/sjoh0704/All-In-One.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false

apigateway:
  replicas: 1


