apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-url
  namespace: {{ .Release.Namespace }}
data:
  PRODUCT_SERVICE_URL: 'http://product.{{ .Release.Namespace }}.svc:8080'
  USER_SERVICE_URL: 'http://user.{{ .Release.Namespace }}.svc:8080'
  CART_SERVICE_URL: 'http://cart.{{ .Release.Namespace }}.svc:8080'
  ORDER_SERVICE_URL: 'http://order.{{ .Release.Namespace }}.svc:8080'  

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-db
  namespace: {{ .Release.Namespace }}
data:
  MONGO_HOST: 'rating-db.{{ .Release.Namespace }}.svc:27017'
